import Browser as B
safari = B.Browser()
print(safari)
safari.request("google")
safari.request("ifpb")
safari.request("uol")
safari.request("record")
print(safari)
safari.request("g1")
safari.request("tsi")
print(safari)